version: '3.8'

services:
  ton-bot:
    build: .
    container_name: ton_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Пробрасываем файл базы данных, чтобы сохранить данные пользователей
      - ./bot_users.db:/app/bot_users.db
    networks:
      - web-network

networks:
  web-network:
    external: true
